### ISSUE TITLE
Tip.. LocalSettings

### ISSUE THREAD

**Issue by robov** [mneimne/docker-mediawiki#2]
A tip for docs... include the settings to get this working.. just a sample of the localsettings.php

Add this to your localsettings.php

`f ( $_SERVER['REMOTE_ADDR'] == '127.0.0.1' ) {
 $wgGroupPermissions['*']['read'] = true;
 $wgGroupPermissions['*']['edit'] = true;
}

wfLoadExtension( 'VisualEditor' );

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Optional: Set VisualEditor as the default for anonymous users
// otherwise they will have to switch to VE
// $wgDefaultUserOptions['visualeditor-editor'] = "visualeditor";

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';

// OPTIONAL: Enable VisualEditor's experimental code features
#$wgDefaultUserOptions['visualeditor-enable-experimental'] = 1;

$wgVisualEditorAvailableNamespaces = [
    NS_MAIN => true,
    NS_USER => true,
    102 => true,
    "_merge_strategy" => "array_plus"
];

$wgVirtualRestConfig['modules']['parsoid'] = array(
	// URL to the Parsoid instance
	// Use port 8142 if you use the Debian package
	'url' => 'http://localhost:8000',
	// Parsoid "domain", see below (optional)
	'domain' => 'localhost',
	// Parsoid "prefix", see below (optional)
	'prefix' => 'localhost'
);`

**Comment by steadyops-dev** [comment]
Hi @robov ,

Thanks for the suggestion, I will review it and include in the documentation.

**Comment by robov** [comment]
Than YOU for creating the package

**Comment by steadyops-dev** [comment]
I think I will leave it to the user to copy/paste the LocalSettings.php file as he might enable different plug-ins

**Comment by robov** [comment]
I think that is a good thing... AND document that they might need to add something
