### ISSUE TITLE
Question : Error loading data from server: apierror-visualeditor-docserver-http-error: (curl error: 7) Couldn't connect to server. Would you like to retry?

### ISSUE THREAD

**Issue by robov** [mneimne/docker-mediawiki#3]
I am integrating your work in my setup, but now I get : Error loading data from server: apierror-visualeditor-docserver-http-error: (curl error: 7) Couldn't connect to server. Would you like to retry?

I did have it running before (but I guess I changes something) ... any idea where to look ?

**Comment by robov** [comment]
It looks like a parsoid issue, but I have not changed the config.yaml
But I am running behind a reverse proxy on a private ip for the wiki container

**Comment by robov** [comment]
ps. I am running wiki 1.3 instead of your 1.29

**Comment by robov** [comment]
oops.. parsoid was not running

**Comment by steadyops-dev** [comment]
weird, Parsoid should always be running as it is managed by Supervisord. I will try to replicate the issue locally meanwhile can you share supervisord log file.

**Comment by robov** [comment]
No.. it was not your code.. it was my mistake ...

**Comment by robov** [comment]
nothing wrong with your code
